name: Cargo Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    types: [ checks_requested ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Boost
      run: sudo apt-get update && sudo apt-get install -y libboost-all-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
